### PR TITLE
add logout mechanism

### PR DESCRIPTION
**Pull request by sepehr-safari**
added a Logout button in navbar to clear localStorage and do a logout from current profile.

### CODE REVIEW

**Comment by DanConwayDev** [comment]
Thanks for the contribution @sepehr-safari. Do you think there should be a warning that this will delete the backup? I assume most people use this to backup their profile, but I've done no research to support this :)

Another idea would be to ensure backup are stored against the pubkey and enable users to backup profiles for multiple pubkeys.

**Comment by sepehr-safari** [comment]
I think showing a warning is a good idea, until you find a better approach to backup those data. I believe storing them in localStorage is not a good idea. someone might has a couple of accounts and wants to edit their metadata and backup all of them. I think a good approach is to integrate this tool with [Pinstr.app](https://pinstr.app). I will develop some features to support such backups. what do you think?

**Comment by DanConwayDev** [comment]
> I think showing a warning is a good idea, until you find a better approach to backup those data.

The best approach I could come up with is having a relay that retains historic versions and returns them upon request. This could be a niche relay that has been modified to store only profile events and also retain historic versions or a standard relay that stores historic version but only returns them if a particular filter is set.

> I believe storing them in localStorage is not a good idea.

What's your concern with this?

I think it's better than not having an easy way to backup and restore this data.
1) users can visit the client to backup their profile periodically or just before they try out a new client
2) users dont have to download anything to file away (although they can); they just visit the site and, if it's their first time, sign in
3) the data is usually quite small so it doesn't massively bloat localStorage

There are lots of problems with this approach to backup: 
1) users have to both know about the profile wipe problem and visit the site for it to be useful. Most nostr users probably haven't visited the site and only will if they have their profile wiped and it probably won't be able to solve their problem.
2) users keep having to revisit to backup
3) they might clear their cache without realising they are wiping their backups.

> I think a good approach is to integrate this tool with [Pinstr.app](https://pinstr.app/)

In what way?

> someone might has a couple of accounts and wants to edit their metadata and backup all of them...I will develop some features to support such backups. what do you think?

This sounds great. Your contributions would be most welcome :). What sort of features do you have in mind?

**Comment by sepehr-safari** [comment]
Why don't you just use [https://github.com/nostr-protocol/nips/blob/master/78.md](https://github.com/nostr-protocol/nips/blob/master/78.md) for backing-up user data ?
I think that would be the best practice, so far.

**Comment by DanConwayDev** [comment]
Great idea. For some reason this didn't occur to me at the time!

**Pull request merged**
